-- ============================================
-- Script de creación de base de datos PostgreSQL
-- Para el proyecto Vestidos de Fiesta
-- ============================================

-- Tabla: garments (Prendas/Vestidos)
-- Esta tabla almacena la información de los vestidos de fiesta
CREATE TABLE IF NOT EXISTS public.garments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Información básica
    brand TEXT NOT NULL,
    title TEXT NOT NULL,
    size TEXT NOT NULL,
    color TEXT NOT NULL,
    description TEXT NOT NULL,
    
    -- URL del video (almacenado en Supabase Storage o externo)
    -- NOTA: Se usa camelCase (videoUrl) para coincidir con el código TypeScript
    "videoUrl" TEXT NOT NULL,
    
    -- Campos opcionales
    price NUMERIC(10, 2),
    slug TEXT,
    material TEXT,
    occasion TEXT,
    style_notes TEXT
);

-- Índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_garments_slug ON public.garments(slug);
CREATE INDEX IF NOT EXISTS idx_garments_brand ON public.garments(brand);
CREATE INDEX IF NOT EXISTS idx_garments_created_at ON public.garments(created_at DESC);

-- Tabla: articles (Artículos del blog)
-- Esta tabla almacena los artículos del blog relacionados con las prendas
CREATE TABLE IF NOT EXISTS public.articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- Información del artículo
    slug TEXT NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT, -- Contenido HTML del artículo
    image_url TEXT, -- URL de la imagen principal (puede ser un video)
    
    -- Relación con la prenda asociada
    garment_id BIGINT REFERENCES public.garments(id) ON DELETE SET NULL
);

-- Índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_articles_slug ON public.articles(slug);
CREATE INDEX IF NOT EXISTS idx_articles_garment_id ON public.articles(garment_id);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON public.articles(created_at DESC);

-- ============================================
-- Row Level Security (RLS) Policies
-- ============================================

-- Habilitar RLS en la tabla garments
ALTER TABLE public.garments ENABLE ROW LEVEL SECURITY;

-- Política de lectura: todos pueden leer las prendas
CREATE POLICY "Enable read access for all users on garments" 
    ON public.garments 
    FOR SELECT 
    USING (true);

-- Política de inserción: todos pueden insertar (ajustar según necesidades de autenticación)
CREATE POLICY "Enable insert access for all users on garments" 
    ON public.garments 
    FOR INSERT 
    WITH CHECK (true);

-- Política de actualización: todos pueden actualizar (ajustar según necesidades de autenticación)
CREATE POLICY "Enable update access for all users on garments" 
    ON public.garments 
    FOR UPDATE 
    USING (true)
    WITH CHECK (true);

-- Política de eliminación: todos pueden eliminar (ajustar según necesidades de autenticación)
CREATE POLICY "Enable delete access for all users on garments" 
    ON public.garments 
    FOR DELETE 
    USING (true);

-- Habilitar RLS en la tabla articles
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Política de lectura: todos pueden leer los artículos
CREATE POLICY "Enable read access for all users on articles" 
    ON public.articles 
    FOR SELECT 
    USING (true);

-- Política de inserción: todos pueden insertar (ajustar según necesidades de autenticación)
CREATE POLICY "Enable insert access for all users on articles" 
    ON public.articles 
    FOR INSERT 
    WITH CHECK (true);

-- Política de actualización: todos pueden actualizar (ajustar según necesidades de autenticación)
CREATE POLICY "Enable update access for all users on articles" 
    ON public.articles 
    FOR UPDATE 
    USING (true)
    WITH CHECK (true);

-- Política de eliminación: todos pueden eliminar (ajustar según necesidades de autenticación)
CREATE POLICY "Enable delete access for all users on articles" 
    ON public.articles 
    FOR DELETE 
    USING (true);

-- ============================================
-- Comentarios en las tablas y columnas
-- ============================================

COMMENT ON TABLE public.garments IS 'Tabla que almacena la información de los vestidos de fiesta';
COMMENT ON COLUMN public.garments.id IS 'Identificador único de la prenda';
COMMENT ON COLUMN public.garments.brand IS 'Marca del vestido';
COMMENT ON COLUMN public.garments.title IS 'Título/nombre del vestido';
COMMENT ON COLUMN public.garments.size IS 'Talla del vestido (XS, S, M, L, XL, etc.)';
COMMENT ON COLUMN public.garments.color IS 'Color del vestido';
COMMENT ON COLUMN public.garments.description IS 'Descripción detallada del vestido';
COMMENT ON COLUMN public.garments."videoUrl" IS 'URL del video del vestido (almacenado en Supabase Storage o externo)';
COMMENT ON COLUMN public.garments.price IS 'Precio del vestido (opcional)';
COMMENT ON COLUMN public.garments.slug IS 'Slug único para URLs amigables (generado automáticamente)';
COMMENT ON COLUMN public.garments.material IS 'Materiales del vestido (opcional)';
COMMENT ON COLUMN public.garments.occasion IS 'Ocasiones para las que es apropiado el vestido (opcional)';
COMMENT ON COLUMN public.garments.style_notes IS 'Notas de estilo del vestido (opcional)';

COMMENT ON TABLE public.articles IS 'Tabla que almacena los artículos del blog relacionados con las prendas';
COMMENT ON COLUMN public.articles.id IS 'Identificador único del artículo';
COMMENT ON COLUMN public.articles.slug IS 'Slug único para URLs amigables';
COMMENT ON COLUMN public.articles.title IS 'Título del artículo';
COMMENT ON COLUMN public.articles.excerpt IS 'Resumen/extracto del artículo';
COMMENT ON COLUMN public.articles.content IS 'Contenido HTML completo del artículo';
COMMENT ON COLUMN public.articles.image_url IS 'URL de la imagen principal del artículo (puede ser un video)';
COMMENT ON COLUMN public.articles.garment_id IS 'ID de la prenda asociada al artículo (opcional)';

-- ============================================
-- NOTAS IMPORTANTES:
-- ============================================
-- 1. Las políticas RLS están configuradas para permitir acceso completo a todos los usuarios.
--    Si necesitas autenticación, deberás modificar las políticas para usar auth.uid().
--
-- 2. El campo "videoUrl" en garments almacena URLs. Los archivos de video se almacenan
--    en Supabase Storage en el bucket 'videos' (no es parte de este script SQL).
--    NOTA: Se usa camelCase con comillas dobles para que coincida exactamente con el código TypeScript.
--
-- 3. El campo slug se genera automáticamente en la aplicación usando la función slugify(),
--    pero puedes crear un trigger en PostgreSQL si prefieres generarlo automáticamente.
--
-- 5. Para crear el bucket de storage 'videos' en Supabase:
--    - Ve a Storage en el panel de Supabase
--    - Crea un nuevo bucket llamado 'videos'
--    - Configura las políticas de acceso según tus necesidades

