import type { Garment } from '../types';

const VIDEOS = [
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video1.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video2.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video3.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video4.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video5.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video6.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video7.mp4',
  'https://storage.googleapis.com/aistudio-hosting/venice-videos/video8.mp4',
];

const SIZES = ['XS', 'S', 'M', 'L', 'XL'];

export const defaultGarments: Garment[] = [
  {
    id: 1001,
    brand: 'Marchesa Notte',
    title: 'Vestido "Cielo Estrellado"',
    slug: 'vestido-cielo-estrellado-1001',
    size: SIZES[1],
    color: 'Azul Noche',
    videoUrl: VIDEOS[0],
    description: 'Un diseño de ensueño que evoca una noche estrellada. Este vestido presenta un corpiño bordado con pedrería y una falda de tul vaporosa que te hará sentir como en un cuento de hadas.',
    created_at: new Date('2024-07-20T10:00:00Z').toISOString(),
    price: 2450.00,
    material: 'Tul, Pedrería, Satén',
    occasion: 'Gala, Boda de Noche, Baile de Graduación',
    style_notes: 'Escote corazón, falda línea A, bordado a mano',
  },
  {
    id: 1002,
    brand: 'Badgley Mischka',
    title: 'Vestido "Glamour de Hollywood"',
    slug: 'vestido-glamour-de-hollywood-1002',
    size: SIZES[2],
    color: 'Dorado',
    videoUrl: VIDEOS[1],
    description: 'Destila el glamour de la época dorada de Hollywood con este vestido de lentejuelas. Su silueta entallada y su brillo sutil capturarán todas las miradas.',
    created_at: new Date('2024-07-19T10:00:00Z').toISOString(),
    price: 2890.00,
    material: 'Lentejuelas, Crepé',
    occasion: 'Alfombra Roja, Fiesta de Año Nuevo, Evento de Gala',
    style_notes: 'Corte columna, escote asimétrico, abertura lateral',
  },
  {
    id: 1003,
    brand: 'Tadashi Shoji',
    title: 'Vestido "Jardín Secreto"',
    slug: 'vestido-jardin-secreto-1003',
    size: SIZES[2],
    color: 'Verde Esmeralda',
    videoUrl: VIDEOS[2],
    description: 'Un vestido romántico con delicados apliques florales en 3D sobre encaje. Su diseño evoca un paseo por un jardín encantado al anochecer.',
    created_at: new Date('2024-07-18T10:00:00Z').toISOString(),
    price: 2100.00,
    material: 'Encaje, Organza, Flores 3D',
    occasion: 'Boda de día, Cóctel en jardín, Bautizo',
    style_notes: 'Cuello halter, largo midi, cintura marcada',
  },
  {
    id: 1004,
    brand: 'Adrianna Papell',
    title: 'Vestido "Brillo de Metrópolis"',
    slug: 'vestido-brillo-de-metropolis-1004',
    size: SIZES[3],
    color: 'Plata',
    videoUrl: VIDEOS[3],
    description: 'Inspirado en las luces de la ciudad, este vestido está completamente adornado con cuentas y cristales, creando un efecto deslumbrante con cada movimiento.',
    created_at: new Date('2024-07-17T10:00:00Z').toISOString(),
    price: 1950.50,
    material: 'Malla bordada, Cuentas de cristal',
    occasion: 'Fiesta de Noche, Cóctel, Boda',
    style_notes: 'Silueta recta, mangas cortas, cuello barco',
  },
  {
    id: 1005,
    brand: 'Vera Wang',
    title: 'Vestido "Silueta Minimalista"',
    slug: 'vestido-silueta-minimalista-1005',
    size: SIZES[1],
    color: 'Negro',
    videoUrl: VIDEOS[4],
    description: 'La elegancia reside en la simplicidad. Este vestido de crepé negro de Vera Wang ofrece un corte impecable y una caída perfecta para un look sofisticado y moderno.',
    created_at: new Date('2024-07-16T10:00:00Z').toISOString(),
    price: 3200.00,
    material: 'Crepé de seda',
    occasion: 'Evento formal, Cena de negocios, Cóctel',
    style_notes: 'Corte recto, escote asimétrico, minimalista',
  },
  {
    id: 1006,
    brand: 'Carolina Herrera',
    title: 'Vestido "Elegancia Clásica"',
    slug: 'vestido-elegancia-clasica-1006',
    size: SIZES[2],
    color: 'Rojo Amapola',
    videoUrl: VIDEOS[5],
    description: 'Un vestido icónico que define la elegancia. Con una falda voluminosa y un cuerpo ajustado, este diseño de Carolina Herrera es atemporal y absolutamente chic.',
    created_at: new Date('2024-07-15T10:00:00Z').toISOString(),
    price: 4500.00,
    material: 'Tafetán de seda',
    occasion: 'Gala, Ópera, Boda formal',
    style_notes: 'Falda con volumen, cuerpo entallado, sin tirantes',
  },
  {
    id: 1007,
    brand: 'Oscar de la Renta',
    title: 'Vestido "Fantasía Floral"',
    slug: 'vestido-fantasia-floral-1007',
    size: SIZES[3],
    color: 'Estampado Floral',
    videoUrl: VIDEOS[6],
    description: 'Una obra de arte textil. Este vestido de Oscar de la Renta presenta un vibrante estampado floral sobre mikado de seda, ideal para un evento primaveral.',
    created_at: new Date('2024-07-14T10:00:00Z').toISOString(),
    price: 5100.00,
    material: 'Mikado de seda',
    occasion: 'Boda de día, Evento benéfico, Garden party',
    style_notes: 'Estampado exclusivo, bolsillos laterales, escote palabra de honor',
  },
  {
    id: 1008,
    brand: 'Pronovias',
    title: 'Vestido "Sueño de Sirena"',
    slug: 'vestido-sueno-de-sirena-1008',
    size: SIZES[1],
    color: 'Blanco Marfil',
    videoUrl: VIDEOS[7],
    description: 'Diseñado para realzar la figura, este vestido de corte sirena de Pronovias está confeccionado en encaje chantilly y termina en una espectacular cola.',
    created_at: new Date('2024-07-13T10:00:00Z').toISOString(),
    price: 3800.00,
    material: 'Encaje Chantilly, Crepé',
    occasion: 'Boda civil, Ceremonia de gala, Renovación de votos',
    style_notes: 'Corte sirena, espalda de encaje transparente, cola larga',
  },
  {
    id: 1009,
    brand: 'Rosa Clará',
    title: 'Vestido "Romance Moderno"',
    slug: 'vestido-romance-moderno-1009',
    size: SIZES[4],
    color: 'Rosa Cuarzo',
    videoUrl: VIDEOS[0],
    description: 'La combinación perfecta de romance y modernidad. Este vestido de Rosa Clará presenta líneas limpias con un toque de pedrería en la cintura.',
    created_at: new Date('2024-07-12T10:00:00Z').toISOString(),
    price: 2950.00,
    material: 'Georgette, Pedrería',
    occasion: 'Madrina de boda, Cóctel, Evento formal de día',
    style_notes: 'Corte imperio, manga capa, cinturón joya',
  },
  {
    id: 1010,
    brand: 'Michael Kors',
    title: 'Vestido "Audacia Metálica"',
    slug: 'vestido-audacia-metalica-1010',
    size: SIZES[2],
    color: 'Bronce',
    videoUrl: VIDEOS[1],
    description: 'Un vestido para la mujer audaz y segura. Confeccionado en un tejido metálico plisado, este diseño de Michael Kors es perfecto para no pasar desapercibida.',
    created_at: new Date('2024-07-11T10:00:00Z').toISOString(),
    price: 1800.00,
    material: 'Tejido metálico plisado',
    occasion: 'Fiesta de noche, Discoteca, Evento de moda',
    style_notes: 'Plisado, cuello halter, largo asimétrico',
  },
  {
    id: 1011,
    brand: 'Ralph Lauren',
    title: 'Vestido "Sofisticación Royal"',
    slug: 'vestido-sofisticacion-royal-1011',
    size: SIZES[3],
    color: 'Azul Marino',
    videoUrl: VIDEOS[2],
    description: 'La elegancia atemporal de Ralph Lauren se materializa en este vestido de terciopelo. Su color profundo y su corte clásico lo convierten en un fondo de armario indispensable.',
    created_at: new Date('2024-07-10T10:00:00Z').toISOString(),
    price: 2600.00,
    material: 'Terciopelo de seda',
    occasion: 'Cena de gala, Evento de invierno, Boda formal',
    style_notes: 'Manga larga, cuello Perkins, silueta entallada',
  },
  {
    id: 1012,
    brand: 'Elie Saab',
    title: 'Vestido "Bordado Celestial"',
    slug: 'vestido-bordado-celestial-1012',
    size: SIZES[1],
    color: 'Nude',
    videoUrl: VIDEOS[3],
    description: 'Una obra maestra de la alta costura. Este vestido de Elie Saab está adornado con miles de cristales y perlas bordados a mano sobre un tul ilusión.',
    created_at: new Date('2024-07-09T10:00:00Z').toISOString(),
    price: 9500.00,
    material: 'Tul, Cristales, Perlas',
    occasion: 'Alfombra Roja, Boda de lujo, Gala benéfica',
    style_notes: 'Bordado integral, efecto transparencia, capa de tul',
  },
  {
    id: 1013,
    brand: 'Zuhair Murad',
    title: 'Vestido "Opulencia Barroca"',
    slug: 'vestido-opulencia-barroca-1013',
    size: SIZES[4],
    color: 'Borgoña',
    videoUrl: VIDEOS[4],
    description: 'Inspirado en la opulencia del barroco, este vestido de Zuhair Murad presenta ricos bordados dorados sobre un suntuoso terciopelo de color vino.',
    created_at: new Date('2024-07-08T10:00:00Z').toISOString(),
    price: 11000.00,
    material: 'Terciopelo, Hilo de oro',
    occasion: 'Gala de invierno, Evento de la realeza',
    style_notes: 'Bordado dorado, mangas abullonadas, escote profundo',
  },
  {
    id: 1014,
    brand: 'Jenny Packham',
    title: 'Vestido "Dama de Cristal"',
    slug: 'vestido-dama-de-cristal-1014',
    size: SIZES[2],
    color: 'Champagne',
    videoUrl: VIDEOS[5],
    description: 'Un vestido etéreo y deslumbrante, adornado con una cascada de cristales de Swarovski. Jenny Packham crea una pieza digna de una estrella.',
    created_at: new Date('2024-07-07T10:00:00Z').toISOString(),
    price: 6200.00,
    material: 'Georgette, Cristales de Swarovski',
    occasion: 'Boda, Fiesta de compromiso, Gala',
    style_notes: 'Adornado con cristales, mangas capa, silueta fluida',
  },
  {
    id: 1015,
    brand: 'Monique Lhuillier',
    title: 'Vestido "Susurro de Tul"',
    slug: 'vestido-susurro-de-tul-1015',
    size: SIZES[3],
    color: 'Lila',
    videoUrl: VIDEOS[6],
    description: 'Ligero como una pluma, este vestido de Monique Lhuillier está confeccionado con capas y capas de tul de seda en un delicado tono pastel.',
    created_at: new Date('2024-07-06T10:00:00Z').toISOString(),
    price: 4800.00,
    material: 'Tul de seda',
    occasion: 'Baile de debutantes, Boda de primavera, Gala',
    style_notes: 'Falda voluminosa, escote palabra de honor, cinturón de satén',
  },
  {
    id: 1016,
    brand: 'Badgley Mischka',
    title: 'Vestido "Rubí Apasionado"',
    slug: 'vestido-rubi-apasionado-1016',
    size: SIZES[1],
    color: 'Rojo Rubí',
    videoUrl: VIDEOS[7],
    description: 'Un vestido que irradia pasión y poder. Confeccionado en un intenso crepé rojo, presenta un dramático detalle de volantes en el hombro.',
    created_at: new Date('2024-07-05T10:00:00Z').toISOString(),
    price: 2550.00,
    material: 'Crepé elástico',
    occasion: 'Cóctel, Evento de San Valentín, Cena formal',
    style_notes: 'Volante asimétrico, corte tubo, color vibrante',
  },
  {
    id: 1017,
    brand: 'Tadashi Shoji',
    title: 'Vestido "Encaje Imperial"',
    slug: 'vestido-encaje-imperial-1017',
    size: SIZES[1],
    color: 'Azul Real',
    videoUrl: VIDEOS[0],
    description: 'La majestuosidad del encaje en un vibrante azul. Este vestido de Tadashi Shoji es perfecto para la invitada que busca destacar con elegancia.',
    created_at: new Date('2024-07-04T10:00:00Z').toISOString(),
    price: 2300.00,
    material: 'Encaje, Neopreno',
    occasion: 'Madrina de boda, Bautizo, Evento formal',
    style_notes: 'Contraste de texturas, falda péplum, largo a la rodilla',
  },
  {
    id: 1018,
    brand: 'Adrianna Papell',
    title: 'Vestido "Noche de Lentejuelas"',
    slug: 'vestido-noche-de-lentejuelas-1018',
    size: SIZES[0],
    color: 'Negro y Plata',
    videoUrl: VIDEOS[1],
    description: 'Un diseño moderno y divertido con un patrón geométrico de lentejuelas. Perfecto para bailar toda la noche con estilo y comodidad.',
    created_at: new Date('2024-07-03T10:00:00Z').toISOString(),
    price: 1750.00,
    material: 'Lentejuelas, Malla',
    occasion: 'Fiesta de fin de año, Cóctel, Noche de chicas',
    style_notes: 'Patrón Art Déco, manga larga, corto',
  },
  {
    id: 1019,
    brand: 'Marchesa Notte',
    title: 'Vestido "Princesa de Porcelana"',
    slug: 'vestido-princesa-de-porcelana-1019',
    size: SIZES[2],
    color: 'Blanco y Azul',
    videoUrl: VIDEOS[2],
    description: 'Inspirado en la delicada porcelana china, este vestido presenta un exquisito bordado floral azul sobre un fondo blanco inmaculado.',
    created_at: new Date('2024-07-02T10:00:00Z').toISOString(),
    price: 3100.00,
    material: 'Organza bordada',
    occasion: 'Boda en la playa, Evento de verano, Bautizo',
    style_notes: 'Bordado floral, falda de té, escote ilusión',
  },
  {
    id: 1020,
    brand: 'Carolina Herrera',
    title: 'Vestido "Lazo Escultural"',
    slug: 'vestido-lazo-escultural-1020',
    size: SIZES[1],
    color: 'Fucsia',
    videoUrl: VIDEOS[3],
    description: 'Una declaración de moda audaz. Este vestido corto de Carolina Herrera se define por un gran lazo escultural en el hombro, creando un impacto visual inolvidable.',
    created_at: new Date('2024-07-01T10:00:00Z').toISOString(),
    price: 3600.00,
    material: 'Mikado',
    occasion: 'Cóctel, Presentación de moda, Boda moderna',
    style_notes: 'Lazo gigante, corte recto, mini',
  },
];