export function getFriendlySupabaseError(error: any): string {
    const supabaseError = error.supabaseError;
    
    if (!supabaseError) {
        return error.message || 'Ocurrió un error desconocido. Revisa la consola para más detalles.';
    }

    // NEW: Error for missing table (relation does not exist)
    if (supabaseError.code === '42P01') {
        const tableNameMatch = supabaseError.message.match(/relation "(.*?)" does not exist/);
        const tableName = tableNameMatch ? tableNameMatch[1] : 'articles';
        
        return `Error de Base de Datos: La tabla '${tableName}' no existe.
\nEsta tabla es necesaria para la nueva funcionalidad del blog.
\nSolución: Ve a tu panel de Supabase, entra al "SQL Editor" y ejecuta el siguiente comando para crear la tabla:

CREATE TABLE public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  slug TEXT,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  image_url TEXT,
  garment_id BIGINT REFERENCES public.garments(id) ON DELETE SET NULL
);
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.articles FOR SELECT USING (true);
`;
    }

    // Error for missing column
    if (supabaseError.code === '42703' && supabaseError.message?.includes('column')) {
        const columnNameMatch = supabaseError.message.match(/column "(.*?)" does not exist/) ?? supabaseError.message.match(/Could not find the '(.*?)' column/);
        const columnName = (columnNameMatch && columnNameMatch[1]) ? columnNameMatch[1] : 'desconocida';
        
        return `Error de Sincronización con la Base de Datos:
\nLa columna '${columnName}' no se encontró en la tabla 'garments'.
\nEsto suele ocurrir cuando la aplicación se actualiza con nuevos campos (como 'precio' o 'color') pero la base de datos no.
\nSolución: Ve a tu panel de Supabase, abre la tabla 'garments' y añade una nueva columna llamada '${columnName}'. Asegúrate de que el tipo de dato sea correcto (ej: 'text', 'numeric') y que permita valores nulos (marca 'Is Nullable').`;
    }

    // Error for wrong data type (e.g., decimal in integer column)
    if (supabaseError.code === '22P02' && (supabaseError.message?.includes('bigint') || supabaseError.message?.includes('integer'))) {
        const valueMatch = supabaseError.message.match(/invalid input syntax for type (?:bigint|integer): "(.*?)"/);
        const badValue = valueMatch ? valueMatch[1] : 'decimal';
        
        return `Error de Tipo de Dato en la Base de Datos:
\nLa base de datos no puede guardar un valor con decimales (como '${badValue}') en la columna 'price' porque está configurada para aceptar solo números enteros.
\nSolución: Ve a tu panel de Supabase, abre la tabla 'garments' y cambia el tipo de la columna 'price'.
\n1. Selecciona la columna 'price'.
\n2. Haz clic en 'Edit column'.
\n3. Cambia el 'Type' a 'numeric' o 'float8'.
\n4. Guarda los cambios.`;
    }

    return error.message || `Ocurrió un error con la base de datos: ${supabaseError.message}`;
}